apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: memecoin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-registry>/memecoin-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: x-api-key
            - name: COINGECKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: coingecko-api-key
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: memecoin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <your-registry>/memecoin-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"