apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: celery-vpa
  namespace: memecoin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 1000m
        memory: 2Gi